name: flood_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Updated for better compatibility

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9 
  http: ^1.2.0   
  path_provider: ^2.1.2 
  path: ^1.8.3
  
  firebase_core: ^2.27.0
  firebase_storage: ^11.7.0
  firebase_auth: ^4.17.8

  cloud_firestore: ^4.15.8
  shared_preferences: ^2.5.4
  url_launcher: ^6.2.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0 # Updated for better linting with latest SDK


flutter:
  uses-material-design: true
